In [1]:
# This exercise focuses on applying standardization to a dataset containing numerical values.
# The dataset used is 'Wholesale customers data.csv', which contains annual spending in monetary
# units across various product categories (e.g., Fresh, Milk, Grocery, etc.) for wholesale clients.
# The goal is to load the dataset using pandas and apply the standard scaler method to transform
# all numerical features so that they share the same scale (mean = 0, standard deviation = 1).
# This step is essential for ensuring that models relying on distance metrics (e.g., KNN, SVM)
# are not biased by differences in feature magnitudes.

import pandas as pd
dataset = 'https://raw.githubusercontent.com/TrainingByPackt/Data-Science-with-Python/refs/heads/master/Chapter01/Data/Wholesale%20customers%20data.csv'
df = pd.read_csv(dataset, header=0)

In [2]:
# The 'Channel' column indicates the type of customer:
# 1 = Horeca (Hotel/Restaurant/Café)
# 2 = Retail

# The 'Region' column indicates the geographical region of the customer:
# 1 = Lisbon
# 2 = Oporto
# 3 = Other Region

df

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen
0,2,3,12669,9656,7561,214,2674,1338
1,2,3,7057,9810,9568,1762,3293,1776
2,2,3,6353,8808,7684,2405,3516,7844
3,1,3,13265,1196,4221,6404,507,1788
4,2,3,22615,5410,7198,3915,1777,5185
5,2,3,9413,8259,5126,666,1795,1451
6,2,3,12126,3199,6975,480,3140,545
7,2,3,7579,4956,9426,1669,3321,2566
8,1,3,5963,3648,6192,425,1716,750
9,2,3,6006,11093,18881,1159,7425,2098
10,2,3,3366,5403,12974,4400,5977,1744
11,2,3,13146,1124,4523,1420,549,497
12,2,3,31714,12319,11757,287,3881,2931
13,2,3,21217,6208,14982,3095,6707,602
14,2,3,24653,9465,12091,294,5058,2168
15,1,3,10253,1114,3821,397,964,412
16,2,3,1020,8816,12121,134,4508,1080
17,1,3,5876,6157,2933,839,370,4478
18,2,3,18601,6327,10099,2205,2767,3181
19,1,3,7780,2495,9464,669,2518,501
20,2,3,17546,4519,4602,1066,2259,2124
21,1,3,5567,871,2010,3383,375,569
22,1,3,31276,1917,4469,9408,2381,4334
23,2,3,26373,36423,22019,5154,4337,16523
24,2,3,22647,9776,13792,2915,4482,5778
25,2,3,16165,4230,7595,201,4003,57
26,1,3,9898,961,2861,3151,242,833
27,1,3,14276,803,3045,485,100,518
28,2,3,4113,20484,25957,1158,8604,5206
29,1,3,43088,2100,2609,1200,1107,823
...,...,...,...,...,...,...,...,...
410,1,3,6633,2096,4563,1389,1860,1892
411,1,3,2126,3289,3281,1535,235,4365
412,1,3,97,3605,12400,98,2970,62
413,1,3,4983,4859,6633,17866,912,2435
414,1,3,5969,1990,3417,5679,1135,290
415,2,3,7842,6046,8552,1691,3540,1874
416,2,3,4389,10940,10908,848,6728,993
417,1,3,5065,5499,11055,364,3485,1063
418,2,3,660,8494,18622,133,6740,776
419,1,3,8861,3783,2223,633,1580,1521
420,1,3,4456,5266,13227,25,6818,1393
421,2,3,17063,4847,9053,1031,3415,1784
422,1,3,26400,1377,4172,830,948,1218
423,2,3,17565,3686,4657,1059,1803,668
424,2,3,16980,2884,12232,874,3213,249
425,1,3,11243,2408,2593,15348,108,1886
426,1,3,13134,9347,14316,3141,5079,1894
427,1,3,31012,16687,5429,15082,439,1163
428,1,3,3047,5970,4910,2198,850,317
429,1,3,8607,1750,3580,47,84,2501
430,1,3,3097,4230,16483,575,241,2080
431,1,3,8533,5506,5160,13486,1377,1498
432,1,3,21117,1162,4754,269,1328,395
433,1,3,1982,3218,1493,1541,356,1449
434,1,3,16731,3922,7994,688,2371,838
435,1,3,29703,12051,16027,13135,182,2204
436,1,3,39228,1431,764,4510,93,2346
437,2,3,14531,15488,30243,437,14841,1867
438,1,3,10290,1981,2232,1038,168,2125
439,1,3,2787,1698,2510,65,477,52

In [3]:
# Check for missing data before preprocessing
# This step ensures there are no NaN values that could affect scaling or model performance.
# The result shows all columns contain only valid integers (int64) and no missing data,
# so there is no need to use df.dropna().

null_ = df.isna().any()
dtypes = df.dtypes
info = pd.concat([null_,dtypes],axis = 1,keys = ['Null', 'type'])
print(info)

                   Null   type
Channel           False  int64
Region            False  int64
Fresh             False  int64
Milk              False  int64
Grocery           False  int64
Frozen            False  int64
Detergents_Paper  False  int64
Delicassen        False  int64

In [4]:
# Perform standard scaling on the dataset using StandardScaler
# This step transforms all columns to have a mean of 0 and a standard deviation of 1.
# It ensures that features with larger magnitudes do not dominate the model training.
# This is crucial for models that rely on distance or gradient-based optimization.

from sklearn import preprocessing
std_scale = preprocessing.StandardScaler().fit_transform(df)
scaled_frame = pd.DataFrame(std_scale, columns=df.columns)
scaled_frame.head()

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen
0,1.448652,0.590668,0.052933,0.523568,-0.041115,-0.589367,-0.043569,-0.066339
1,1.448652,0.590668,-0.391302,0.544458,0.170318,-0.270136,0.086407,0.089151
2,1.448652,0.590668,-0.447029,0.408538,-0.028157,-0.137536,0.133232,2.243293
3,-0.690297,0.590668,0.100111,-0.624020,-0.392977,0.687144,-0.498588,0.093411
4,1.448652,0.590668,0.840239,-0.052396,-0.079356,0.173859,-0.231918,1.299347